language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- node
- lts/*
script:
- npm test
env:
  global:
    secure: Fw6vDx2Qe1KYq1Rmg/pUZylvdx3lfbwvMmukq06I5vYrA+NDpzcJAO9oETwiRXHC/yriulmC/A9sVO+kfsC4XyPtizr1PaO0NtEySB9tAvhELjHOAtjIcbNL2+kCHgCS1a8oywDghsAC+xpYoFTjO6onbOlSmQWV+wTuy8/M3hto62q0c2BrqlaxasfIwByveD9RGdKEh+bIt17FJvuDC1O/LjeqqGIFVlzOd4GFnilTcVp8DQPTbbR2j+t+nDobkWXWc0P49UdWQF6l08JXiT8uiAgOPPbirGphlkkJDGVgot2oSvGH6ZfxnR5YQl9WLngVbV4k7ex3Rw3qavRfguGh4DteN1mnVGE+f/3JIVtCsq0IuXjaQrsBTyvwh0FiJI0+Xu18ZFWQyeJDQIKwIJ1yveuvxTb1eJE68fZOu9khWqftz0T+A69soJrdCeEXFRP4jLB8jwaGDiwuFyUURNHoxYdvGOJnTTOL36EeYYcFXsJNMQ02h96grkDuq9U3dRPZMyPBabowKEh4sTb6/lOAkf5X/chJcFZncDt4Mx4lMdW9SBT6oDCHhpOlWK0Vkhu+YTnQvPlqHaWuDztrn4ZsfQTiK8sQ5HMKrMDBBLXZy5bLRYsLEFhSmKefP6WZuMZrNwNJ86S1zSdS/TYUJWdkJlKwocSz9SkHWDYLr7A=
